/* Seed payload. Imported by scripts/seed.ts to populate the database. */

export const SEED_RESOURCES = [
  // open-source (10)
  { slug:"hackaday-io", name:"Hackaday.io", url:"https://hackaday.io", category:"open-source", capLabel:"Community", description:"Publish projects, dev logs and connect with hardware hackers.", isPick:true, isVerified:true, pricing:"Free", platforms:["Web"], tags:["Community","Projects"] },
  { slug:"github", name:"GitHub", url:"https://github.com", category:"open-source", capLabel:"Open Source", description:"Host engineering files, firmware, docs and version history.", isVerified:true, pricing:"Freemium", platforms:["Web"], tags:["Open Source"] },
  { slug:"gitlab", name:"GitLab", url:"https://gitlab.com", category:"open-source", capLabel:"Open Source", description:"Code, CI/CD and private project collaboration.", isVerified:true, pricing:"Freemium", platforms:["Web"], tags:["Open Source"] },
  { slug:"oshwa", name:"OSHWA", url:"https://oshwa.org", category:"open-source", capLabel:"Certification", description:"Open hardware standards, certification and project directory.", isPick:true, isVerified:true, pricing:"Free", platforms:["Web"], tags:["Certification","Standards"] },
  { slug:"arduino-hub", name:"Arduino Project Hub", url:"https://projecthub.arduino.cc", category:"open-source", capLabel:"Projects", description:"Arduino projects, tutorials and reference designs.", isVerified:true, pricing:"Free", platforms:["Web"], tags:["Projects"] },
  { slug:"instructables", name:"Instructables", url:"https://instructables.com", category:"open-source", capLabel:"Tutorials", description:"DIY, electronics and mechanical project tutorials.", isVerified:true, pricing:"Free", platforms:["Web"], tags:["Tutorials"] },
  { slug:"hackster", name:"Hackster.io", url:"https://hackster.io", category:"open-source", capLabel:"Community", description:"Dev board, IoT and embedded project community.", isVerified:true, pricing:"Free", platforms:["Web"], tags:["Community"] },
  { slug:"adafruit-learn", name:"Adafruit Learning", url:"https://learn.adafruit.com", category:"open-source", capLabel:"Learning", description:"Electronics, sensors, CircuitPython and open hardware guides.", isPick:true, isVerified:true, pricing:"Free", platforms:["Web"], tags:["Learning"] },
  { slug:"sparkfun-learn", name:"SparkFun Learn", url:"https://learn.sparkfun.com", category:"open-source", capLabel:"Learning", description:"Hardware tutorials and project resources for makers.", isVerified:true, pricing:"Free", platforms:["Web"], tags:["Learning"] },
  { slug:"thingiverse", name:"Thingiverse", url:"https://thingiverse.com", category:"open-source", capLabel:"3D Models", description:"3D-printable models and mechanical part files.", isVerified:true, pricing:"Free", platforms:["Web"], tags:["3D Models"] },
  // marketplaces (8)
  { slug:"tindie", name:"Tindie", url:"https://tindie.com", category:"crowdfunding", capLabel:"Marketplace", description:"The marketplace for independent hardware and maker products.", isVerified:true, pricing:"Free to browse", platforms:["Web"], tags:["Marketplace"] },
  { slug:"eehub", name:"EEHub", url:"https://eehub.io", category:"crowdfunding", capLabel:"Project Platform", description:"Electronics projects, engineering files and hardware resources.", isPick:true, isPartner:true, isVerified:true, pricing:"Freemium", platforms:["Web"], tags:["Projects"] },
  { slug:"lectronz", name:"Lectronz", url:"https://lectronz.com", category:"crowdfunding", capLabel:"Marketplace", description:"A marketplace for independent hardware creators.", isVerified:true, pricing:"Free to browse", platforms:["Web"], tags:["Marketplace"] },
  { slug:"groupgets", name:"GroupGets", url:"https://groupgets.com", category:"crowdfunding", capLabel:"Group Buy", description:"Small-batch group buys, pre-orders and crowdfunding.", isVerified:true, pricing:"Free to browse", platforms:["Web"], tags:["Group Buy"] },
  { slug:"elecrow-m", name:"Elecrow Marketplace", url:"https://elecrow.com", category:"crowdfunding", capLabel:"Marketplace", description:"Open hardware and maker product marketplace.", isVerified:true, pricing:"Free to browse", platforms:["Web"], tags:["Marketplace"] },
  { slug:"etsy-e", name:"Etsy (Electronics)", url:"https://etsy.com", category:"crowdfunding", capLabel:"Marketplace", description:"Handmade and small-batch electronics sales channel.", isVerified:true, pricing:"Free to browse", platforms:["Web"], tags:["Marketplace"] },
  { slug:"ebay-e", name:"eBay Electronics", url:"https://ebay.com", category:"crowdfunding", capLabel:"Marketplace", description:"Global market for electronics and components.", isVerified:true, pricing:"Free to browse", platforms:["Web"], tags:["Marketplace"] },
  { slug:"amzn-lp", name:"Amazon Launchpad", url:"https://amazon.com/launchpad", category:"crowdfunding", capLabel:"Marketplace", description:"Channel for emerging brands and innovative products.", isVerified:true, pricing:"Free to browse", platforms:["Web"], tags:["Marketplace"] },
  // tools (12)
  { slug:"kicad", name:"KiCad", url:"https://kicad.org", category:"tools", capLabel:"EDA", description:"Open-source schematic capture and PCB design.", isPick:true, isVerified:true, pricing:"Free", platforms:["Win","macOS","Linux"], tags:["EDA","PCB"] },
  { slug:"altium", name:"Altium Designer", url:"https://altium.com", category:"tools", capLabel:"EDA", description:"Professional electronic design and PCB development.", isVerified:true, pricing:"Paid", platforms:["Win"], tags:["EDA"] },
  { slug:"easyeda", name:"EasyEDA", url:"https://easyeda.com", category:"tools", capLabel:"EDA", description:"Browser-based schematic, PCB and simulation tool.", isVerified:true, pricing:"Freemium", platforms:["Web"], tags:["EDA"] },
  { slug:"fusion-e", name:"Fusion Electronics", url:"https://autodesk.com/products/fusion-360/electronics-engineer", category:"tools", capLabel:"ECAD/MCAD", description:"Electronics and mechanical co-design.", isVerified:true, pricing:"Paid", platforms:["Win","macOS"], tags:["ECAD"] },
  { slug:"flux", name:"Flux", url:"https://flux.ai", category:"tools", capLabel:"EDA", description:"Cloud PCB tool with collaboration and AI assistance.", isVerified:true, pricing:"Freemium", platforms:["Web"], tags:["EDA","AI"] },
  { slug:"librepcb", name:"LibrePCB", url:"https://librepcb.org", category:"tools", capLabel:"EDA", description:"Open-source, cross-platform electronic design tool.", isVerified:true, pricing:"Free", platforms:["Win","macOS","Linux"], tags:["EDA"] },
  { slug:"ltspice", name:"LTspice", url:"https://analog.com/ltspice", category:"tools", capLabel:"Simulation", description:"Analog and power circuit simulation.", isVerified:true, pricing:"Free", platforms:["Win","macOS"], tags:["Simulation"] },
  { slug:"circuitjs", name:"CircuitJS", url:"https://falstad.com/circuit", category:"tools", capLabel:"Simulation", description:"Browser-based interactive circuit simulator.", isVerified:true, pricing:"Free", platforms:["Web"], tags:["Simulation"] },
  { slug:"platformio", name:"PlatformIO", url:"https://platformio.org", category:"tools", capLabel:"Toolchain", description:"Embedded build, library and toolchain platform.", isPick:true, isVerified:true, pricing:"Freemium", platforms:["Win","macOS","Linux"], tags:["Toolchain"] },
  { slug:"arduino-ide", name:"Arduino IDE", url:"https://arduino.cc/en/software", category:"tools", capLabel:"IDE", description:"Programming tool for Arduino and compatible boards.", isVerified:true, pricing:"Free", platforms:["Win","macOS","Linux"], tags:["IDE"] },
  { slug:"zephyr", name:"Zephyr Project", url:"https://zephyrproject.org", category:"tools", capLabel:"RTOS", description:"Open-source RTOS for embedded devices.", isVerified:true, pricing:"Free", platforms:["Cross"], tags:["RTOS"] },
  { slug:"freecad", name:"FreeCAD", url:"https://freecad.org", category:"tools", capLabel:"CAD", description:"Open-source parametric mechanical CAD.", isVerified:true, pricing:"Free", platforms:["Win","macOS","Linux"], tags:["CAD"] },
  // manufacturing (10)
  { slug:"seeed-fusion", name:"Seeed Studio Fusion", url:"https://seeedstudio.com/prototype-pcb-assembly.html", category:"manufacturing", capLabel:"PCB · PCBA · Mfg", description:"PCB, PCBA, prototype and small-batch manufacturing.", isPick:true, isPartner:true, isVerified:true, pricing:"Quote", platforms:["Web"], tags:["PCB","PCBA"] },
  { slug:"jlcpcb", name:"JLCPCB", url:"https://jlcpcb.com", category:"manufacturing", capLabel:"PCB · 3D · CNC", description:"PCB, assembly, 3D printing and machining.", isVerified:true, pricing:"Quote", platforms:["Web"], tags:["PCB"] },
  { slug:"pcbway", name:"PCBWay", url:"https://pcbway.com", category:"manufacturing", capLabel:"PCB · CNC · Mfg", description:"PCB, PCBA, CNC and small-batch manufacturing.", isVerified:true, pricing:"Quote", platforms:["Web"], tags:["PCB","CNC"] },
  { slug:"oshpark", name:"OSH Park", url:"https://oshpark.com", category:"manufacturing", capLabel:"PCB", description:"Prototype and open-hardware PCB manufacturing.", isPick:true, isVerified:true, pricing:"Quote", platforms:["Web"], tags:["PCB"] },
  { slug:"macrofab", name:"MacroFab", url:"https://macrofab.com", category:"manufacturing", capLabel:"Cloud Mfg", description:"Cloud electronics manufacturing and supply chain.", isVerified:true, pricing:"Quote", platforms:["Web"], tags:["Manufacturing"] },
  { slug:"circuithub", name:"CircuitHub", url:"https://circuithub.com", category:"manufacturing", capLabel:"PCBA", description:"Electronics manufacturing for hardware teams.", isVerified:true, pricing:"Quote", platforms:["Web"], tags:["PCBA"] },
  { slug:"aisler", name:"Aisler", url:"https://aisler.net", category:"manufacturing", capLabel:"PCB", description:"European PCB prototyping and assembly.", isVerified:true, pricing:"Quote", platforms:["Web"], tags:["PCB"] },
  { slug:"eurocircuits", name:"Eurocircuits", url:"https://eurocircuits.com", category:"manufacturing", capLabel:"PCB · DFM", description:"European PCB manufacturing, assembly and DFM.", isVerified:true, pricing:"Quote", platforms:["Web"], tags:["PCB","DFM"] },
  { slug:"protolabs", name:"Protolabs", url:"https://protolabs.com", category:"manufacturing", capLabel:"CNC · Molding", description:"CNC, injection molding, sheet metal, rapid proto.", isVerified:true, pricing:"Quote", platforms:["Web"], tags:["CNC","Molding"] },
  { slug:"xometry", name:"Xometry", url:"https://xometry.com", category:"manufacturing", capLabel:"On-demand Mfg", description:"On-demand machining and manufacturing network.", isVerified:true, pricing:"Quote", platforms:["Web"], tags:["Manufacturing"] },
  // crowdfunding (5)
  { slug:"crowdsupply", name:"Crowd Supply", url:"https://crowdsupply.com", category:"crowdfunding", capLabel:"Crowdfunding", description:"Crowdfunding and sales focused on open hardware.", isPick:true, isVerified:true, pricing:"Free to browse", platforms:["Web"], tags:["Crowdfunding"] },
  { slug:"kickstarter", name:"Kickstarter", url:"https://kickstarter.com", category:"crowdfunding", capLabel:"Crowdfunding", description:"Crowdfunding for creative, design and tech products.", isVerified:true, pricing:"Free to browse", platforms:["Web"], tags:["Crowdfunding"] },
  { slug:"indiegogo", name:"Indiegogo", url:"https://indiegogo.com", category:"crowdfunding", capLabel:"Crowdfunding", description:"Global crowdfunding for tech and consumer products.", isVerified:false, linkOk:false, pricing:"Free to browse", platforms:["Web"], tags:["Crowdfunding"] },
  { slug:"backerkit", name:"BackerKit", url:"https://backerkit.com", category:"crowdfunding", capLabel:"Pledge Mgmt", description:"Crowdfunding, pre-orders and backer management.", isVerified:true, pricing:"Quote", platforms:["Web"], tags:["Pledge Mgmt"] },
  { slug:"crowdox", name:"CrowdOx", url:"https://crowdox.com", category:"crowdfunding", capLabel:"Order Mgmt", description:"Post-campaign order and backer management.", isVerified:true, pricing:"Quote", platforms:["Web"], tags:["Order Mgmt"] },
  // components (5)
  { slug:"digikey", name:"DigiKey", url:"https://digikey.com", category:"components", capLabel:"Distributor", description:"Component sourcing, datasheets and design resources.", isVerified:true, pricing:"Catalog", platforms:["Web"], tags:["Distributor"] },
  { slug:"mouser", name:"Mouser Electronics", url:"https://mouser.com", category:"components", capLabel:"Distributor", description:"Component sourcing, new products and technical data.", isVerified:true, pricing:"Catalog", platforms:["Web"], tags:["Distributor"] },
  { slug:"octopart", name:"Octopart", url:"https://octopart.com", category:"components", capLabel:"Search", description:"Component parameter, stock and price search.", isVerified:true, pricing:"Free", platforms:["Web"], tags:["Search"] },
  { slug:"snapmagic", name:"SnapMagic", url:"https://snapmagic.com", category:"components", capLabel:"CAD Models", description:"Symbols, footprints and CAD models for parts.", isVerified:true, pricing:"Freemium", platforms:["Web"], tags:["CAD Models"] },
  { slug:"ultralib", name:"Ultra Librarian", url:"https://ultralibrarian.com", category:"components", capLabel:"CAD Library", description:"Component CAD models and design libraries.", isVerified:true, pricing:"Freemium", platforms:["Web"], tags:["CAD Library"] },
];

export const SEED_SOURCES = [
  { name:"GitHub Trending (Topics)", method:"API", frequency:"2h", trust:"High", dailyCap:4, errorRate:"0.4%", status:"active" },
  { name:"Crowd Supply", method:"RSS", frequency:"6h", trust:"High", dailyCap:3, errorRate:"0%", status:"active" },
  { name:"Hackaday.io", method:"API", frequency:"3h", trust:"High", dailyCap:3, errorRate:"1.1%", status:"active" },
  { name:"Seeed Studio Blog", method:"RSS", frequency:"12h", trust:"Medium", dailyCap:2, errorRate:"0%", status:"active" },
  { name:"Kickstarter Technology", method:"Crawl", frequency:"12h", trust:"Low", dailyCap:2, errorRate:"4.2%", status:"active" },
  { name:"DigiKey New Products", method:"API", frequency:"24h", trust:"High", dailyCap:2, errorRate:"0%", status:"active" },
  { name:"Indiegogo Technology", method:"RSS", frequency:"12h", trust:"Low", dailyCap:1, errorRate:"18%", status:"paused" },
];

// Published discoveries for two prior days + one needs-review batch for the admin demo.
function d(o: any) {
  return Object.assign({ chips: [], relatedTags: [], saveCount: 0, commentCount: 0, license: "—", availability: "—", aiScore: 75 }, o);
}

export const SEED_DISCOVERIES = [
  // ---- published today (publishDate set, status=published) ----
  d({ title:"Milk-V Duo S RISC-V Dev Board", category:"crowdfunding", sourceName:"Sipeed", icon:"🟩", summary:"High-performance RISC-V board with Ethernet, Wi-Fi 6 and rich peripherals.", why:"A capable RISC-V base that drives demand for the modules and shields makers sell here.", chips:["RISC-V","Ethernet","Linux"], saveCount:42, commentCount:8, license:"Open Hardware", availability:"In production", relatedTags:["risc"], status:"published", aiScore:81 }),
  d({ title:"ESP32-S3 Air Quality Sensor", category:"crowdfunding", sourceName:"LilyGO", icon:"🌫️", summary:"Compact module with PMSA003I, BME680 and TVOC for air monitoring.", why:"Ready reference design for IoT sellers building environmental products.", chips:["ESP32-S3","Sensors","IoT"], saveCount:55, commentCount:11, isSponsored:true, license:"Proprietary", availability:"Available", relatedTags:["esp32"], status:"published", aiScore:79 }),
  d({ title:"Open Source LCR Meter", category:"components", sourceName:"Aidan Lawrence", icon:"📟", summary:"DIY LCR meter with 100kHz bandwidth and excellent accuracy.", why:"Bench tool your buyers pair with the components and kits they buy on Tindie.", chips:["Test","Measurement","Open Source"], saveCount:73, commentCount:14, isPick:true, license:"CERN-OHL-S", availability:"Files published", relatedTags:["test"], status:"published", aiScore:88 }),
  d({ title:"MechDog Quadruped Robot", category:"crowdfunding", sourceName:"Kickstarter", icon:"🐕", summary:"Open-source, 3D printable quadruped robot for research and education.", why:"A reference platform that pulls demand for servos, sensors and controllers.", chips:["Robotics","3D Print","Servos"], saveCount:61, commentCount:15, license:"Open Hardware", availability:"Funding — 142%", relatedTags:["robot"], status:"published", aiScore:84 }),
  d({ title:"KiCad Interactive BOM Plugin", category:"tools", sourceName:"Hackaday.io", icon:"🧩", summary:"Visualize, filter and validate BOM data directly inside KiCad.", why:"Cuts assembly errors for sellers doing their own small-batch builds.", chips:["KiCad","BOM","EDA"], saveCount:48, commentCount:6, license:"MIT", availability:"Free download", relatedTags:["tools"], status:"published", aiScore:77 }),
  d({ title:"Tang Nano 20K Learning Board", category:"crowdfunding", sourceName:"Sipeed", icon:"🟦", summary:"Low-cost FPGA board with USB-C, HDMI and on-board debugger.", why:"Affordable FPGA entry point growing the niche your FPGA sellers serve.", chips:["FPGA","USB-C","HDMI"], saveCount:31, commentCount:4, license:"Proprietary", availability:"Available", relatedTags:["fpga"], status:"published", aiScore:72 }),
  d({ title:"Open RP2350 audio shield released", category:"open-source", sourceName:"GitHub", icon:"🔓", summary:"24-bit I²S codec shield with gerbers and KiCad files under CERN-OHL.", why:"A drop-in audio front-end sound sellers can fork instead of designing fresh.", chips:["RP2350","Audio","Open Source"], saveCount:39, commentCount:5, license:"CERN-OHL-S", availability:"Repo public", relatedTags:["audio"], status:"published", aiScore:80 }),
  d({ title:"Low-cost USB-C PD sink controller", category:"components", sourceName:"DigiKey", icon:"🔌", summary:"Single-chip 100W PD negotiation under $0.40/unit, now in stock.", why:"Cheap PD power input for any board — a BOM line affecting margins platform-wide.", chips:["USB-C PD","Power"], saveCount:28, commentCount:3, license:"Commercial", availability:"In stock", relatedTags:["power"], status:"published", aiScore:69 }),
  d({ title:"CircuitPython 9.2 adds native CAN", category:"tools", sourceName:"Adafruit", icon:"🌈", summary:"New release brings CAN bus, improved BLE and smaller builds.", why:"Lowers the barrier for CAN projects — relevant to industrial sellers.", chips:["CircuitPython","CAN","BLE"], saveCount:67, commentCount:9, license:"MIT", availability:"Released", relatedTags:["can"], status:"published", aiScore:77 }),
  d({ title:"Meshtastic LoRa node v3 hardware", category:"open-source", sourceName:"GitHub", icon:"📡", summary:"Open hardware handheld with solar charging and machined case.", why:"Off-grid mesh demand pulls LoRa modules and antennas sold by makers.", chips:["LoRa","Mesh","Open Source"], saveCount:52, commentCount:12, license:"GPL-3.0", availability:"Repo public", relatedTags:["lora"], status:"published", aiScore:83 }),
  d({ title:"Flux adds AI net-list autorouting", category:"tools", sourceName:"Hackaday.io", icon:"🧮", summary:"Browser PCB tool ships an AI assistant that suggests routing for selected nets.", why:"Speeds up board bring-up for sellers iterating on small-batch designs.", chips:["EDA","AI","Routing"], saveCount:36, commentCount:7, license:"Freemium", availability:"Live", relatedTags:["tools"], status:"published", aiScore:74 }),
  d({ title:"New 0.4mm-pitch FPC connector stocked", category:"components", sourceName:"Mouser", icon:"🧷", summary:"Low-profile flex connector now available in single quantities.", why:"Common BOM part for compact wearables and camera boards makers sell.", chips:["Connector","FPC","Components"], saveCount:19, commentCount:2, license:"Commercial", availability:"In stock", relatedTags:["power"], status:"published", aiScore:66 }),
  // ---- needs_review batch (for admin demo) ----
  d({ title:"16-channel pocket logic analyzer hits 120%", category:"crowdfunding", sourceName:"Crowd Supply", icon:"🚀", summary:"USB-C, 100 MS/s analyzer with open firmware and a sigrok-compatible decoder.", why:"Affordable bench tool your buyers will pair with the dev boards they buy on Tindie.", chips:["Test Equipment","USB-C","Open Source"], aiScore:88, status:"needs_review", relatedTags:["test"] }),
  d({ title:"XIAO ESP32-C6 adds Wi-Fi 6 + Thread", category:"crowdfunding", sourceName:"Seeed Studio", icon:"🔧", summary:"Thumb-sized module bringing 802.15.4 for Matter projects, stencil files day one.", why:"Matter-ready core for smart-home makers; Fusion stencil means fast small-batch runs.", chips:["ESP32-C6","Thread","Matter"], aiScore:79, flag:"sponsored", isSponsored:true, status:"needs_review", relatedTags:["esp32"] }),
  d({ title:'"Revolutionary" AI gadget — vague specs', category:"crowdfunding", sourceName:"Kickstarter", icon:"❓", summary:"Campaign with bold claims but no schematics, BOM or verifiable specs.", why:"Flagged: unverifiable claims; likely not a fit for the daily edition.", chips:["AI","Unverified"], aiScore:41, flag:"risk", status:"needs_review", relatedTags:[] }),
  d({ title:"ESP32 weather station (reposted x12 sites)", category:"crowdfunding", sourceName:"GitHub", icon:"🌦️", summary:"A common ESP32 weather build reposted across many aggregators this week.", why:"Flagged: duplicate cluster; not novel enough for a daily slot.", chips:["ESP32","Weather"], aiScore:52, flag:"dup", status:"needs_review", relatedTags:["esp32"] }),
];
